[package]
name = "ig_edge"
version = "0.2.0-unstable"
description = "An implementation of Info Edges."
license = "MIT"
edition = "2021"

[dependencies]
ig_tr = { version = "0.2.0-unstable", path = "../ig_tr" }
ig_desc = { version = "0.2.0-unstable", path = "../ig_desc" }
